sudo: required 
dist: xenial 
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
      - jrgnichodevel@gmail.com
      - levi.armstrong@gmail.com
    on_failure: always

env:
  matrix:
    - ROS_DISTRO="kinetic" 
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic" 
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
      UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="melodic"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
      UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="melodic"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
      UPSTREAM_WORKSPACE=file
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - source .ci_config/travis.sh
